---

name: "build and run docker"

'on':
  pull_request:

jobs:
  docker-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ls
        run: |
          ls
      - name: echo
        run: |
          echo "this is an echo"
#      - name: setup blubber
#        run: |
#          blubber() {
#            if [ $# -lt 2 ]; then
#              echo 'Usage: blubber config.yaml variant'
#              return 1
#            fi
#            curl -s -H 'content-type: application/yaml' --data-binary @"$1" https://blubberoid.wikimedia.org/v1/"$2"
#          }

      - name: run blubber
        run: |
          curl -s -H 'content-type: application/yaml' --data-binary @".pipeline/blubber.yaml" https://blubberoid.wikimedia.org/v1/quarry-test
      - name: run more blubber
        run: |
          blubber .pipeline/blubber.yaml quarry-test | docker build --tag blubber-quarry:01 --file - . ; docker run blubber-quarry:01
      - name: run docker
        run: |
          docker run hello-world
    #container:
    #  image: alpine:latest
    ##  cmd:
    ##    CMD ["echo", "Hello from github Actions!"]
    #steps:
    #  - name: echo something
    #    run: |
    #      echo "foo"
