---

name: "Push Notification"

'on':
  pull_request:
  #pull_request: [opened, closed]

#on: [push, pull_request, create, closed]

jobs:
  notification:
    runs-on: ubuntu-latest
    name: Alert to IRC
    steps:
      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#          PRNUMBER: ${{ toJson(github.pull_request.html.href) }}
        run: |
          message="${{ github.actor }} ${{ github.event.action }} ${{ github.event.pull_request._links.html.href }}"
          echo ${message}

