---

name: "test open and close pr"

'on':
  pull_request:
    types: [opened, closed]

jobs:
  notification:
    runs-on: ubuntu-latest
    name: Alert to IRC
    steps:
      - name: echo
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: open
        run: |
          echo 1
        if: github.event.action == 'opened' || github.event.action == 'reopened'
      - name: close
        run: |
          echo 2
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
