---

name: "test open and close pr"

'on':
  pull_request:
#    types: [opened, closed]

jobs:
  notification:
    runs-on: ubuntu-latest
    name: Alert to IRC
    steps:
      - name: echo
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: open
        run: |
          echo 1
        if: github.event.action == 'opened' || github.event.action == 'reopened'
      - name: close
        run: |
          echo 2
        if: github.event.action == 'closed' && github.event.pull_request.merged == true

      - uses: actions/checkout@v2
      - name: git log
        run: |
          git branch
          git fetch
          git branch 
      - name: git log more
        run: |
          #git log
          inital_commit=$(git log origin/main..origin/${{ github.head_ref }} --pretty=%H | tail -n1)
          echo "this is an echo ${inital_commit}"
          task=$(git log -n 1 ${inital_commit} | tail -n1 | grep "^    Bug: T[0-9]*$" | awk '{print $2}')
          if [ -n "${task}" ]; then
            echo "found ${task}"
          else
            echo "it would appear that ${task} is empty"
          fi
          #git log origin/main..origin/get-from-git --pretty=%H | tail -n1

